### ISSUE TITLE
Unreal 5.3 and Quest 3 support. 

### ISSUE THREAD

**Issue by JustinHoang1703** [oculus-samples/Unreal-HandGameplay#17]
Hi Jason! Your plug-in is super cool. I wonder do you have a timeline if it will be support on Quest 3 with Unreal 5.3 Oculus fork by chance? Cheers!

**Comment by jasonmeisel** [comment]
Hi Justin! This showcase and the plug-in is already working on Quest 3. It is not upgraded to 5.3 yet, but I expect it will just work if you give it a try.

**Comment by elvisguillen** [comment]
@jasonmeisel I attempted to upgrade to 5.3 over the weekend but I keep getting the following error in the HandTrackingFilterComponent.cpp

cannot open source file "XRMotionControllerBase.h"
Cannot open include file: 'XRMotionControllerBase.h': No such file or directory

Looking into the update it seems like the location for it changed from 5.2 to 5.3. In the documentation it seems to be in an XRBase plugin now instead of runtime

https://docs.unrealengine.com/5.3/en-US/API/Plugins/XRBase/FXRMotionControllerBase/
https://docs.unrealengine.com/5.2/en-US/API/Runtime/HeadMountedDisplay/FXRMotionControllerBase/

**Comment by jasonmeisel** [comment]
> @jasonmeisel I attempted to upgrade to 5.3 over the weekend but I keep getting the following error in the HandTrackingFilterComponent.cpp

Thanks for looking into this! This is the same issue we had in upgrading Unreal-SharedSpaces [here](https://github.com/oculus-samples/Unreal-SharedSpaces/commit/c3c698295c9f46004d78f926aea0af671dfb35bd#diff-e10db68decec6419740d1550a99dd38584c44e81c8c422b97b0fa3be1eddfed1).

If you make a similar change in HandTrackingFilter.Build.cs, it should resolve that error.

We plan to upgrade this project to 5.3 soon, but if you're able to get it working in the meantime, feel free to send us a pull request!

**Comment by AlexThiv** [comment]
The update for UE5.3 was just pushed
https://github.com/oculus-samples/Unreal-HandGameplay/commit/ac1e44e5bdccc87311d5294062fcc65b1c2f3136

Let us know if you run into other issues.
