### ISSUE TITLE
Could you clarify the build configuration?

### ISSUE THREAD

**Issue by spayne** [oculus-samples/Unreal-HandGameplay#7]
Hello,

I'm looking to build this against the Oculus unreal fork and wanted to double check the following steps:

> 6. Set HandGameplay as the start-up project and Development Editor as the configuration.
> 7. Hit F5 to build and debug the project

- Are you saying here that I should build Development Editor|x64?  Will that actually work? Across Oculus Link?   I think that would be awesome but as far as I know the Hand APIs won't work using the link.  You do go on in the next step to use F5 to debug so...
- Or should this be Development | Android?
- Or does Development Editor | Android?

Thanks,
Sean

**Comment by lmcquade** [comment]
You should build Development Editor|x64 to build the Editor first.   This is needed in order to open the project in the Editor, and it is needed in order to package the project for other platforms.   The Hand APIs do actually work over link.

You can build Development|Android if you want - but packaging for Android will do this for you anyway.

You do not need to build Development Editor|Android, as there is no Android version of the Editor :)

**Comment by lmcquade** [comment]
Closing issue.  Let me know if you have any more questions.
